server:
  port: 8090
  forward-headers-strategy: native
  compression:
    enabled: false
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  devtools:
    add-properties: false
  output:
    ansi:
      enabled: always
  datasource:
    druid:
      initialSize:  5
      minIdle:  10
      maxActive:  20
      maxWait:  60000
      timeBetweenEvictionRunsMillis:  60000
      minEvictableIdleTimeMillis: 300000
      maxEvictableIdleTimeMillis: 900000
      validationQuery:  SELECT 1 FROM DUAL
      testWhileIdle:  true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled:  true
      statViewServlet:
        enabled:  true
        allow:
        url-pattern: /admin/druid/*
      filter:
        stat:
          enabled:  true
          log-slow-sql: true
          slow-sql-millis:  1000
          merge-sql:  true
        wall:
          config:
            multi-statement-allow:  true
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#
#    # H2 database configuration.
##    driver-class-name: org.h2.Driver
##    url: jdbc:h2:file:~/.halo/db/halo
##    username: admin
##    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/halodb1?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#    username: root
#    password: 111111
#  h2:
#    console:
#      settings:
#        web-allow-others: false
#      path: /h2-console
#      enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
#  flyway:
#    enabled: true
#    locations: classpath:/migration
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
      location: ${java.io.tmpdir}
management:
  health:
    db:
#      enabled: false
  endpoints:
    enabled: false
    web:
      base-path: /api/admin/actuator
      exposure:
        include: ['httptrace', 'metrics','env','logfile','health']
mybatis-plus:
  mapper-locations: classpath*:/mybatis/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#  type-aliases-package: cn.ymotel.dpress.entity
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
#    root: DEBUG
    com.apache.ibatis: DEBUG
    java.sql.Connection: DEBUG
    java.sql.Statement: DEBUG
    java.sql.PreparedStatement: DEBUG
    run.halo.app: DEBUG
  file:
    path: ${user.home}/.halo/logs

halo:
  download-timeout: 5m
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson
      expireAfterWriteInMillis: 120000
#全局本地超时时间 2分钟
  remote:
    default:
      type: mock
      expireAfterWriteInMillis: 120000
#dactor:
#  enabled: false
